# This file is machine-generated - editing it directly is not advised

[[AbstractTrees]]
deps = ["Markdown", "Test"]
git-tree-sha1 = "6621d9645702c1c4e6970cc6a3eae440c768000b"
uuid = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
version = "0.2.1"

[[Base64]]
uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"

[[Currencies]]
deps = ["DelimitedFiles", "Test"]
git-tree-sha1 = "033fd6e1903935bad63a6f1ed0593d2ebcdea012"
uuid = "0fd90b74-7c1f-579e-9252-02cd883047b9"
version = "0.12.0"

[[Dates]]
deps = ["Printf"]
uuid = "ade2ca70-3891-5945-98fb-dc099432e06a"

[[DelimitedFiles]]
deps = ["Mmap"]
uuid = "8bb1440f-4735-579b-a4ab-409b98df4dab"

[[Distributed]]
deps = ["Random", "Serialization", "Sockets"]
uuid = "8ba89e20-285c-5b6f-9357-94700520ee1b"

[[FinancialInstruments]]
deps = ["Currencies", "Dates", "Reexport"]
git-tree-sha1 = "43e49ec20792d65d1b9a42a060acd67412a3ea84"
uuid = "fc5b99d0-3725-11e9-2623-bf561589b708"
version = "0.1.1"

[[FixedPointDecimals]]
deps = ["Printf", "Test"]
git-tree-sha1 = "b17a731934600b835150b7882238e7f06f8be368"
uuid = "fb4d412d-6eee-574d-9565-ede6634db7b0"
version = "0.3.0"

[[InteractiveUtils]]
deps = ["Markdown"]
uuid = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[[Logging]]
uuid = "56ddb016-857b-54e1-b83d-db4d58db5568"

[[Markdown]]
deps = ["Base64"]
uuid = "d6f4376e-aef5-505a-96c1-9c027394607a"

[[Markets]]
deps = ["Dates", "Observables", "Positions", "Reexport"]
path = "C:\\Users\\Eric\\.julia\\dev\\Markets"
uuid = "b44f5480-3750-11e9-03b7-d5e34f572a03"
version = "0.1.1+"

[[Mmap]]
uuid = "a63ad114-7e13-5084-954f-fe012c677804"

[[Observables]]
deps = ["Test"]
git-tree-sha1 = "dc02cec22747d1d10d9f70d8a1c03432b5bfbcd0"
uuid = "510215fc-4207-5dde-b226-833fc4488ee2"
version = "0.2.3"

[[Positions]]
deps = ["FinancialInstruments", "FixedPointDecimals", "Reexport"]
git-tree-sha1 = "2e880619c4115f36c1e72ba45f41369c5c527b58"
uuid = "81d999f0-3725-11e9-2196-fd457307c398"
version = "0.1.1"

[[Printf]]
deps = ["Unicode"]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[[Random]]
deps = ["Serialization"]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[[Reexport]]
git-tree-sha1 = "6b9a637e33dfb9ceff7f01938408c344fa926ce3"
repo-rev = "master"
repo-url = "https://github.com/simonster/Reexport.jl.git"
uuid = "189a3867-3050-52da-a836-e630ba90ab69"
version = "0.2.0+"

[[Serialization]]
uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[[Sockets]]
uuid = "6462fe0b-24de-5631-8697-dd941f90decc"

[[Test]]
deps = ["Distributed", "InteractiveUtils", "Logging", "Random"]
uuid = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[[Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"
